// This file is auto-generated by Convex
// Run `npx convex dev` to regenerate

import type { FunctionArgs } from "convex/server";
import { anyApi } from "convex/server";

// Data models
export type DataModel = {};

// API
export const api = anyApi;

// Query and Mutation types
export type Query = FunctionArgs<"query">;
export type Mutation = FunctionArgs<"mutation">;
export type Action = FunctionArgs<"action">;
